### ISSUE TITLE
cibuildwheel 2.12.2 broke support for Python 3.7

### ISSUE THREAD

**Issue by ShaneHarvey** [pypa/cibuildwheel#1478]
### Description

cibuildwheel 2.12.2 broke support for Python 3.7:
```
+ python -m cibuildwheel --output-dir wheelhouse
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.[16](https://github.com/mongodb-labs/mongo-arrow/actions/runs/4737323741/jobs/8409993937#step:9:17)/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/cibuildwheel/__main__.py", line 247, in <module>
    class PlatformModule(typing.Protocol):
AttributeError: module 'typing' has no attribute 'Protocol'
```

typing.Protocol is new in Python 3.8: https://docs.python.org/3.8/library/typing.html#typing.Protocol

### Build log

https://github.com/mongodb-labs/mongo-arrow/actions/runs/4737323741/jobs/8409993937

### CI config

https://github.com/mongodb-labs/mongo-arrow/blob/main/.github/workflows/release-python.yml

**Comment by henryiii** [comment]
Looks like this happened in https://github.com/pypa/cibuildwheel/pull/1461. Should be a very easy fix, just needs to be from cibuildwheel.typing.Protocol. I _almost_ added these to the disallowed imports I just added! It would have caught this.

**Comment by ShaneHarvey** [comment]
Thanks for the quick fix!
