### ISSUE TITLE
PermissionError during cleaning on Windows runner for CMake FetchContent dependency

### ISSUE THREAD

**Issue by golmschenk** [pypa/cibuildwheel#1523]
### Description

Hello! I'm running into an issue where, for a Windows CI runner, the build fails due to a `PermissionError: [WinError 5] Access is denied`. It appears to be occurring due to a CMake `FetchContent` dependency from a git repository. It seems the build is not properly releasing the git related resources when attempting to clean during the wheel build. The build works fine for both macOS and Linux.

I setup a small example repository demonstrating this issue here: https://github.com/golmschenk/cibuildwheel_fetchcontent_permission_error_example.
The failing build can be seen here: https://github.com/golmschenk/cibuildwheel_fetchcontent_permission_error_example/actions/runs/5270068999/jobs/9529084594.

I found a similar issue (https://github.com/pypa/cibuildwheel/issues/897) with a `PermissionError` occurring on the Windows runner. This appeared to be due to a pip clean bug. However, I've attempted both to set the environment variable to disable pip cleaning (`PIP_NO_CLEAN: "yes"`) and using the non-pip build frontend with cibuildwheel (`CIBW_BUILD_FRONTEND: "build"`), and neither seemed to fix the issue. I also attempted the build on Cirrus CI rather than GitHub Actions and encountered a similar issue.

The full error appears as:
```
    *** Making wheel...
    Traceback (most recent call last):
      File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-4pku3vah\cp37-win32\build\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
        main()
      File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-4pku3vah\cp37-win32\build\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-4pku3vah\cp37-win32\build\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 252, in build_wheel
        metadata_directory)
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-ss4tjy2i\overlay\Lib\site-packages\scikit_build_core\build\__init__.py", line 36, in build_wheel
        editable=False,
      File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-build-env-ss4tjy2i\overlay\Lib\site-packages\scikit_build_core\build\wheel.py", line 288, in _build_wheel_impl
        f"import _{normalized_name}_editable\n".encode(),
      File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.7.9\tools\lib\tempfile.py", line 807, in __exit__
        self.cleanup()
      File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.7.9\tools\lib\tempfile.py", line 811, in cleanup
        _shutil.rmtree(self.name)
      File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.7.9\tools\lib\shutil.py", line 516, in rmtree
        return _rmtree_unsafe(path, onerror)
      File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.7.9\tools\lib\shutil.py", line 395, in _rmtree_unsafe
        _rmtree_unsafe(fullname, onerror)
      File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.7.9\tools\lib\shutil.py", line 395, in _rmtree_unsafe
        _rmtree_unsafe(fullname, onerror)
      File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.7.9\tools\lib\shutil.py", line 395, in _rmtree_unsafe
        _rmtree_unsafe(fullname, onerror)
      [Previous line repeated 3 more times]
      File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.7.9\tools\lib\shutil.py", line 400, in _rmtree_unsafe
        onerror(os.unlink, fullname, sys.exc_info())
      File "C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.7.9\tools\lib\shutil.py", line 398, in _rmtree_unsafe
        os.unlink(fullname)
    PermissionError: [WinError 5] Access is denied: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpwvkc37iy\\build\\_deps\\fortran_stdlib-src\\.git\\objects\\pack\\pack-faae3e6a7f3ee7b73a650fc640815b9d8dbf92df.idx'
```

It seems there may be some issue with how cibuildwheel is preforming the various build steps resulting in the resources not being released correctly before the cleanup. However, if this is an issue in something that cibuildwheel calls, or is a mistake on my part, please let me know.

Thank you for your time!

### Build log

https://github.com/golmschenk/cibuildwheel_fetchcontent_permission_error_example/actions/runs/5270068999/jobs/9529084594

### CI config

https://github.com/golmschenk/cibuildwheel_fetchcontent_permission_error_example/blob/main/.github/workflows/build_wheels.yml

**Comment by joerick** [comment]
This backtrace is inside your build backend, scikit-build-core, not cibuildwheel, so this is more likely to be fixable there. 

I will say that cibuildwheel just ignores cleanup errors on Windows, as we occasionally see sporadic failures there and it's rarely critical. It looks like your case might be a consistent failure, but `shutil.rmtree(temp_dir, ignore_errors=True)` doesn't seem to have many downsides for us.

I'd recommend filing over at https://github.com/scikit-build/scikit-build-core.

**Comment by henryiii** [comment]
There’s a standard trick (used by wheel) for this that I can look into for scikit-build-core, we could switch to this trick for cibuildwheel too, I think.

**Comment by henryiii** [comment]
I'm going to predict that [this only happens](https://github.com/python/cpython/blob/85c4608a3afa6753f04ed4ade1ec1a866aaacf95/Lib/tempfile.py#L796-L798) on Python 3.7, by the way. It looks like this bug [was fixed](https://github.com/python/cpython/blob/40ea37ddae465d7046e2a6b8d9fd80c27f8b2da6/Lib/tempfile.py#L794) in 3.8 (this is when this standard workaround for `shutil.rmtree` was added to TemporaryDirectory).

Since this is TemporaryDirectory, not a direct usage of `shutil.rmtree`, I'll have to write a workaround for that instead of just using the common one for shutil for 3.7. :/

**Comment by henryiii** [comment]
For my education, could you try removing 3.7 from your build and seeing it passes?

**Comment by golmschenk** [comment]
@joerick, thank you for the information and your time! And sorry for the misclassification of the issue!

@henryiii, upgrading to Python 3.8 indeed does seem to resolve the issue. The build can be seen here: https://github.com/golmschenk/cibuildwheel_fetchcontent_permission_error_example/actions/runs/5290893595/jobs/9575683760

For my own use case, I'm fine with simply dropping 3.7 support. Of course, I'm happy to test out applying the workaround if it would be helpful. Please let me know if you would like me to reopen this issue in some fashion over in the scikit-build-core issue tracker.

Thank you much for your time!

**Comment by henryiii** [comment]
Sure, you can reopen there, and I'll prepare a workaround for 3.7 Windows.

**Comment by henryiii** [comment]
(Ironically, preparing for the monthly scikit-build community meeting is interfering with me preparing the fix for scikit-build-core. :) )
