### ISSUE TITLE
Need to support single-sourcing-package-version

### ISSUE THREAD

**Issue by jianlins** [pypa/cibuildwheel#1641]
### Description

It doesn't support this configuration: 
https://packaging.python.org/en/latest/guides/single-sourcing-package-version/

Any suggestions to fix? Error copied below:

```python
determining package name from '/home/runner/work/_actions/pypa/cibuildwheel/v2.16.2'...
installing cibuildwheel from spec '/home/runner/work/_actions/pypa/cibuildwheel/v2.16.2'...
Traceback (most recent call last):
  File "/opt/pipx/.cache/7dc9bfa5da4c2ff/bin/cibuildwheel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/pipx/.cache/7dc9bfa5da4c2ff/lib/python3.11/site-packages/cibuildwheel/__main__.py", line 144, in main
    build_in_directory(args)
  File "/opt/pipx/.cache/7dc9bfa5da4c2ff/lib/python3.11/site-packages/cibuildwheel/__main__.py", line 269, in build_in_directory
    options = compute_options(platform=platform, command_line_arguments=args, env=os.environ)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/.cache/7dc9bfa5da4c2ff/lib/python3.11/site-packages/cibuildwheel/options.py", line 746, in compute_options
    options = Options(platform=platform, command_line_arguments=command_line_arguments, env=env)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/.cache/7dc9bfa5da4c2ff/lib/python3.11/site-packages/cibuildwheel/options.py", line [39](https://github.com/jianlins/quicksectx/actions/runs/6485441584/job/17611516778#step:4:43)8, in __init__
    self.reader = OptionsReader(
                  ^^^^^^^^^^^^^^
  File "/opt/pipx/.cache/7dc9bfa5da4c2ff/lib/python3.11/site-packages/cibuildwheel/options.py", line 215, in __init__
    config_options, config_platform_options = self._load_file(config_file_path)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pipx/.cache/7dc9bfa5da4c2ff/lib/python3.11/site-packages/cibuildwheel/options.py", line 287, in _load_file
    config = tomllib.load(f)
             ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/tomllib/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/tomllib/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/tomllib/_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/tomllib/_parser.py", line 369, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/tomllib/_parser.py", line 6[49](https://github.com/jianlins/quicksectx/actions/runs/6485441584/job/17611516778#step:4:53), in parse_value
    raise suffixed_err(src, pos, "Invalid value")
tomllib.TOMLDecodeError: Invalid value (at line 21, column 9)
Error: Process completed with exit code 1.
```

### Build log

https://github.com/jianlins/quicksectx/actions/runs/6485441584/job/17611516778

### CI config

https://github.com/jianlins/quicksectx/blob/master/.github/workflows/test_build_singleos.yml

**Comment by Czaki** [comment]
you have in `pyproject.toml` `version=version = {attr = "quicksectx.__version__"}` where `version = {attr = "package.__version__"}` is posted in docs.

**Comment by jianlins** [comment]
Oh, just spotted that too. thanks

**Comment by jianlins** [comment]
Oh, just spotted that too. thanks
