### ISSUE TITLE
Building wheel suddenly failing on windows amd64

### ISSUE THREAD

**Issue by aaron-siegel** [pypa/cibuildwheel#1991]
### Description

Our wheel build has abruptly started failing on windows amd64 with this exception:
```
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\normal\Lib\site-packages\cffi\_shimmed_dist_utils.py", line 33, in <module>
        from distutils.msvc9compiler import MSVCCompiler
    ModuleNotFoundError: No module named 'distutils.msvc9compiler'
```
The identical build was working a week ago. There have been no changes to the build file or environment since then.

Since this is buried in cibuildwheel I'm not sure where to start looking to figure out what's happening. Please help! Thank you. Here's the full log of the failing build wheel step.
```
Building cp39-win_amd64 wheel
CPython 3.9 Windows 64bit
Installing Python cp39...
  + Download https://dist.nuget.org/win-x86-commandline/latest/nuget.exe to C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget.exe
  + 'C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget.exe' install python -Version 3.9.13 -FallbackSource https://api.nuget.org/v3/index.json -OutputDirectory 'C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython'
  Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    https://api.nuget.org/v3/index.json
  Attempting to gather dependency information for package 'python.3.9.13' with respect to project 'C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython', targeting 'Any,Version=v0.0'
  Gathering dependency information took 432 ms
  Attempting to resolve dependencies for package 'python.3.9.13' with DependencyBehavior 'Lowest'
  Resolving dependency information took 0 ms
  Resolving actions to install package 'python.3.9.13'
  Resolved actions to install package 'python.3.9.13'
  Retrieving package 'python 3.9.13' from 'nuget.org'.
    GET https://api.nuget.org/v3-flatcontainer/python/3.9.13/python.3.9.13.nupkg
    OK https://api.nuget.org/v3-flatcontainer/python/3.9.13/python.3.9.13.nupkg 3ms
  Installed python 3.9.13 from https://api.nuget.org/v3/index.json to C:\Users\runneradmin\.nuget\packages\python\3.9.13 with content hash Y9rag81Yk0TmyMZjyV1dKBBaCS1VWL1ueAnogL5gbrnc77Xrsij7CafxdHebBWKmtowX4L36naQ7Ayg2qIbEwQ==.
  Adding package 'python.3.9.13' to folder 'C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython'
  Added package 'python.3.9.13' to folder 'C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython'
  Successfully installed 'python 3.9.13' to C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython
  Executing nuget actions took 9.9 sec
                                                             ✓ 13.78s
Setting up build environment...
  + Download https://github.com/pypa/get-virtualenv/blob/20.26.3/public/virtualenv.pyz?raw=true to C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\virtualenv-20.26.3.pyz
  + 'C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe' -sS 'C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\virtualenv-20.26.3.pyz' --activators= --no-periodic-update --pip=24.2 --no-setuptools --no-wheel --python 'C:\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.9.13\tools\python.exe' 'C:\Users\runneradmin\AppData\Local\Temp\cibw-run-utta6obb\cp39-win_amd64\build\venv'
  created virtual environment CPython3.9.13.final.0-64 in 3398ms
    creator CPython3Windows(dest=C:\Users\runneradmin\AppData\Local\Temp\cibw-run-utta6obb\cp39-win_amd64\build\venv, clear=False, no_vcs_ignore=False, global=False)
    seeder FromAppData(download=False, pip=24.2, via=copy, app_data_dir=C:\Users\runneradmin\AppData\Local\pypa\virtualenv)
      added seed packages: pip==24.2
  + python -m pip install --upgrade pip -c 'C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\cibuildwheel\resources\constraints-python39.txt'
  Requirement already satisfied: pip in c:\users\runneradmin\appdata\local\temp\cibw-run-utta6obb\cp39-win_amd64\build\venv\lib\site-packages (24.2)
  + where python
  C:\Users\runneradmin\AppData\Local\Temp\cibw-run-utta6obb\cp39-win_amd64\build\venv\Scripts\python.exe
  C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe
  C:\hostedtoolcache\windows\Python\3.9.13\x64\python.exe
  + python --version
  Python 3.9.13
  + python -c '"import struct; print(struct.calcsize('"'"'P'"'"') * 8)"'
  + where python
  + where pip
  + pip --version
  pip 24.2 from C:\Users\runneradmin\AppData\Local\Temp\cibw-run-utta6obb\cp39-win_amd64\build\venv\lib\site-packages\pip (python 3.9)
                                                              ✓ 8.16s
Installing build tools...
  + python -m pip freeze --all
                                                              ✓ 0.30s
Building wheel...
  + python -m pip wheel 'D:\a\pixeltable-pgserver\pixeltable-pgserver' '--wheel-dir=C:\Users\runneradmin\AppData\Local\Temp\cibw-run-utta6obb\cp39-win_amd64\built_wheel' --no-deps
  Processing d:\a\pixeltable-pgserver\pixeltable-pgserver
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Installing backend dependencies: started
    Installing backend dependencies: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error
    
    Preparing metadata (pyproject.toml) did not run successfully.
    exit code: 1
    
    [40 lines of output]
    Traceback (most recent call last):
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\normal\Lib\site-packages\cffi\_shimmed_dist_utils.py", line 33, in <module>
        from distutils.msvc9compiler import MSVCCompiler
    ModuleNotFoundError: No module named 'distutils.msvc9compiler'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-utta6obb\cp39-win_amd64\build\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
        main()
      File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-utta6obb\cp39-win_amd64\build\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-utta6obb\cp39-win_amd64\build\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\overlay\Lib\site-packages\setuptools\build_meta.py", line 373, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
        exec(code, locals())
      File "<string>", line 3, in <module>
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 146, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\overlay\Lib\site-packages\setuptools\dist.py", line 283, in __init__
        _Distribution.__init__(self, dist_attrs)
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 278, in __init__
        self.finalize_options()
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\overlay\Lib\site-packages\setuptools\dist.py", line 635, in finalize_options
        ep(self)
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\overlay\Lib\site-packages\setuptools\dist.py", line 655, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\normal\Lib\site-packages\cffi\setuptools_ext.py", line 216, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\normal\Lib\site-packages\cffi\setuptools_ext.py", line 71, in add_cffi_module
        _add_c_module(dist, ffi, module_name, source, source_extension, kwds)
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\normal\Lib\site-packages\cffi\setuptools_ext.py", line 109, in _add_c_module
        from cffi._shimmed_dist_utils import Extension, log, mkpath
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-1ivyezik\normal\Lib\site-packages\cffi\_shimmed_dist_utils.py", line 39, in <module>
        raise Exception("This CFFI feature requires distutils. Please install the distutils or setuptools package.") from ex
    Exception: This CFFI feature requires distutils. Please install the distutils or setuptools package.
    [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
  Encountered error while generating package metadata.
  See above for output.
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.
  Error: Command ['python', '-m', 'pip', 'wheel', 'D:\\a\\pixeltable-pgserver\\pixeltable-pgserver', '--wheel-dir=C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-utta6obb\\cp39-win_amd64\\built_wheel', '--no-deps'] failed with code 1. 
```

**Comment by henryiii** [comment]
This was removed in setuptools 74. looks like cffi needs to be updated.

**Comment by aaron-siegel** [comment]
Thanks for the quick response. Is there an easy way to instruct cibuildwheel to use an earlier version of setuptools in the python envs that it creates? If not, what's the workaround?

**Comment by aaron-siegel** [comment]
I figured it out, the dependencies are pulled from our `pyproject.toml`; limiting the `setuptools` version to `<74` fixes it. Thanks for your help.

**Comment by Czaki** [comment]
You may limit the setuptools version in `build-system.requires` section of your pyproject.toml.
