### ISSUE TITLE
ffi.h is not found when building wheel with CPython 3.10

### ISSUE THREAD

**Issue by Hanaasagi** [pypa/cibuildwheel#783]
## Description

I add Python 3.10 to `CIBW_BUILD` in my Github Action. But it failed when building wheel. It seems that `libffi-devel` is not found in the manylinux image (not sure). However, 3.8 and 3.9 was built successfully.

```
fatal error: ffi.h: No such file or directory
```

## Environment

Github Action `pypa/cibuildwheel@v2.0.1`

```
Build options:
  platform: 'linux'
  architectures: {<Architecture.i686: 'i686'>, <Architecture.aarch64: 'aarch64'>, <Architecture.x86_64: 'x86_64'>}
  before_all: ''
  before_build: ''
  before_test: ''
  build_frontend: 'pip'
  build_selector: BuildSelector(build_config='cp36-* cp37-* cp38-* cp39-* cp310-*', prerelease_pythons=True)
  build_verbosity: 0
  dependency_constraints: DependencyConstraintsPosixPath('/opt/pipx/.cache/f019b55f1841d88/lib/python3.8/site-packages/cibuildwheel/resources/constraints.txt'))
  environment: ParsedEnvironment([])
  manylinux_images: {'x86_64': 'quay.io/pypa/manylinux2010_x86_64:2021-07-25-cfe8a6c', 'i686': 'quay.io/pypa/manylinux2010_i686:2021-07-25-cfe8a6c', 'pypy_x86_64': 'quay.io/pypa/manylinux2010_x86_64:2021-07-25-cfe8a6c', 'aarch64': 'quay.io/pypa/manylinux2014_aarch64:2021-07-25-cfe8a6c', 'ppc64le': 'quay.io/pypa/manylinux2014_ppc64le:2021-07-25-cfe8a6c', 's390x': 'quay.io/pypa/manylinux2014_s390x:2021-07-25-cfe8a6c', 'pypy_aarch64': 'quay.io/pypa/manylinux2014_aarch64:2021-07-25-cfe8a6c', 'pypy_i686': 'quay.io/pypa/manylinux2010_i686:2021-07-25-cfe8a6c'}
  output_dir: PosixPath('wheelhouse')
  package_dir: PosixPath('.')
  repair_command: 'auditwheel repair -w {dest_dir} {wheel}'
  test_command: ''
  test_extras: ''
  test_requires: []
  test_selector: TestSelector(build_config='*')
```

## Backtrace

```
        gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/opt/python/cp310-cp310/include/python3.10 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.10/c/_cffi_backend.o
        c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
         #include <ffi.h>
                  ^~~~~~~
        compilation terminated.
        error: command '/opt/rh/devtoolset-8/root/usr/bin/gcc' failed with exit code 1
        ----------------------------------------
        ERROR: Failed building wheel for cffi
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/opt/python/cp310-cp310/lib/python3.10/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/opt/python/cp310-cp310/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/python/cp310-cp310/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpr6f5wcw1', '--quiet', 'cffi>=1.5.0']' returned non-zero exit status 1.
```

The full log: https://github.com/Hanaasagi/pycares/runs/3230989395?check_suite_focus=true

**Comment by henryiii** [comment]
Hmm, wonder if it's related to https://github.com/pypa/manylinux/pull/1159 - though I'm assuming you are using rc4, the current default? Does manylinux2014 work?

**Comment by Hanaasagi** [comment]
I see it used the `quay.io/pypa/manylinux2010_x86_64:2021-07-25-cfe8a6c` image. It's Python 3.10.0b4.

**Comment by Czaki** [comment]
@Hanaasagi your project depends on cffi package which does not provide wheels for python 3.10. https://pypi.org/project/cffi/#files

For Python 3.6-9 it works because it uses wheels for cffi. Python 3.10 its try to build cffi from the source. 

https://cffi.readthedocs.io/en/latest/installation.html

fast googling for `ffi.h centos` shows that there may be a problem with the not standard path. https://stackoverflow.com/questions/31508612/pip-install-unable-to-find-ffi-h-even-though-it-recognizes-libffi

If it is not installed then you could use `CIBW_BEFORE_ALL_LINUX` to install missed package.

**Comment by Hanaasagi** [comment]
Thanks for your reply.
