### ISSUE TITLE
Teardown of virtualenv on Windows can fail

### ISSUE THREAD

**Issue by tseaver** [pypa/cibuildwheel#825]
From [this failure](https://github.com/googleapis/python-crc32c/runs/3601785932?check_suite_focus=true):

```python
  Traceback (most recent call last):
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "C:\Program Files (x86)\pipx\.cache\707837e2618ce4b\Scripts\cibuildwheel.exe\__main__.py", line 7, in <module>
    File "C:\Program Files (x86)\pipx\.cache\707837e2618ce4b\lib\site-packages\cibuildwheel\__main__.py", line 351, in main
      cibuildwheel.windows.build(build_options)
    File "C:\Program Files (x86)\pipx\.cache\707837e2618ce4b\lib\site-packages\cibuildwheel\windows.py", line 424, in build
      shutil.rmtree(venv_dir)
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\shutil.py", line 516, in rmtree
      return _rmtree_unsafe(path, onerror)
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\shutil.py", line 395, in _rmtree_unsafe
      _rmtree_unsafe(fullname, onerror)
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\shutil.py", line 400, in _rmtree_unsafe
      onerror(os.unlink, fullname, sys.exc_info())
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\shutil.py", line 398, in _rmtree_unsafe
      os.unlink(fullname)
  PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmp08aupc62\\Scripts\\python.exe'
```

I suggest passing `ignore_error=True` to the `shutil.rmtree()` [call during teardown](https://github.com/pypa/cibuildwheel/blob/fded547220d97f03121dbb50a9104d7341bea802/cibuildwheel/windows.py#L424).

**Comment by remia** [comment]
Having the same issue [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/runs/3599348746?check_suite_focus=true). Any particular reason this popup now?

**Comment by joerick** [comment]
I don't know why we're starting to see this now. I do see this occasionally on TravisCI, but it appears that it has appear on GHA too now. I'll take a look at the PR.

**Comment by mayeut** [comment]
This seems related to https://github.com/actions/virtual-environments/issues/4086

**Comment by joerick** [comment]
Looks like it was fixed in the GHA image. @tseaver @remia have you seen the issue in the last 24 hours?

**Comment by remia** [comment]
@joerick The issue seems to be solved on our side as well.
